- name: Twitsy - Configuration on EC2 Instance
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  remote_user: ec2-user
  vars:
    dockerhub_repository: "niteshraj"
    # ansible_ssh_private_key_file: "/home/runner/.ssh/my_key_pair"
  tasks:
    - name: Install Docker
      yum:
        name: "{ { item } }"
        state: latest
      loop:
        - docker
        - docker-compose
        - python3

    - name: Start Docker service
      service:
        name: "docker"
        state: started

    - name: Authenticate with DockerHub
      docker_login:
        username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKERHUB_TOKEN') }}"
        
    - name: Pull images and mysql
      docker_image:
        name: "{{ item.image }}"
        source: pull
        tag: "{{ item.tag }}"
        pull_timeout: 600
      loop:
        - { image: "{{ dockerhub_repository }}/fe", tag: latest }
        - { image: "{{ dockerhub_repository }}/be", tag: latest }
        - { image: "mysql", tag: "8.0" }

    - name: Copy file for docker-compose
      copy:
        src: "ansible/template/docker-compose.yml.j2"
        desc: "~/docker-compose.yml"

    - name: Copy init file for mysql conatiner
      copy:
        src: "ansible/template/init.sql.j2"
        desc: "~/dbinit/init.sql"

    # - name: Start conatiners
    #   command: "docker-compose up"
