name: Actions for Twitsy-Program

on:
  push:
    branches:
      - 'Not-Now/**'

jobs:
  Build-and-Push:
    name: Build and Push Image to DockerHub
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Set output variables
        id: constant-output
        run: |
          echo "ECR_REPO_NAME=my-ecr-repo" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push Docker image for frontend
      #   id: image-build-frontend
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     context: frontend
      #     dockerfile: frontend/Dockerfile
      #     tags: niteshraj/twitsyfe:latest

      # - name: Build and push Docker image for backend
      #   id: image-build-backend
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     context: backend
      #     dockerfile: backend/Dockerfile
      #     tags: niteshraj/twitsybe:latest

      #for terraform and ansible
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Terraform apply to create EC2 instance
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd terraform
          terraform init 
          terraform plan
          terraform apply --auto-approve
          #    terraform destroy --auto-approve  # for removing existing Infra on aws  

      - name: Sleep task for delay
        run: |
          sleep 45

      - name: Ansible Runs
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: ansible/playbook.yml # path to your Ansible playbook
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }} # the ssh private key for ansible to use to connect to the servers, stored as "ansible_ssh_private_key" in the GitHub secrets
          inventory: ansible/inventory # the ansible inventory to use, stored as "ansible_inventory" in the GitHub secrets

      #    mkdir -p /home/runner/.ssh/
      #    echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/ec2-key.pem
      #    chmod 600 /home/runner/.ssh/ec2-key.pem
      # - name: Run Ansible playbook for configuration in EC2 instance
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      #   run: |
      #     cd ansible
      #     ansible-playbook playbook.yml
        