name: Actions for Twitsy-Program

on:
  push:
    branches:
      - 'actions/**'

jobs:
  Build-and-Push:
    name: Build and Push Image to Amazon ECR
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Set output variables
        id: constant-output
        run: |
          echo "ECR_REPO_NAME=my-ecr-repo" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to Docker Hub
        run: docker login --username niteshraj --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for frontend
        id: image-build-frontend
        uses: docker/build-push-action@v4
        with:
          push: false
          context: frontend
          dockerfile: frontend/Dockerfile
          tags: niteshraj/twitsyfe:latest
        